stages:
  - build
  - test
  - deploy

variables:
  IMAGE_TAG: latest

build_frontend:
  stage: build
  script:
    - echo "Сборка frontend контейнера..."
    - docker build -t frontend:$IMAGE_TAG ./frontend
    - docker tag frontend:$IMAGE_TAG $HARBOR_URL/$HARBOR_PROJECT/frontend:$IMAGE_TAG
    - echo $HARBOR_PASSWORD | docker login $HARBOR_URL -u $HARBOR_USER --password-stdin
    - docker push $HARBOR_URL/$HARBOR_PROJECT/frontend:$IMAGE_TAG

build_backend:
  stage: build
  script:
    - echo "Сборка backend контейнера..."
    - docker build -t backend:$IMAGE_TAG ./backend
    - docker tag backend:$IMAGE_TAG $HARBOR_URL_TAG/$HARBOR_PROJECT/backend:$IMAGE_TAG
    - echo $HARBOR_PASSWORD | docker login $HARBOR_URL -u $HARBOR_USER --password-stdin
    - docker push $HARBOR_URL/$HARBOR_PROJECT/backend:$IMAGE_TAG

build_nginx:
  stage: build
  script:
    - echo "Сборка nginx контейнера..."
    - docker build -t nginx:$IMAGE_TAG ./nginx
    - docker tag nginx:$IMAGE_TAG $HARBOR_URL_TAG/$HARBOR_PROJECT/nginx:$IMAGE_TAG
    - echo $HARBOR_PASSWORD | docker login $HARBOR_URL -u $HARBOR_USER --password-stdin
    - docker push $HARBOR_URL/$HARBOR_PROJECT/nginx:$IMAGE_TAG

test_frontend:
  stage: test
  image: node:22.13.1-alpine
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - corepack enable
    - corepack prepare pnpm@latest-10 --activate
    - pnpm config set store-dir .pnpm-store
  script:
    - echo "Устанавливаем зависимости..."
    - cd frontend
    - pnpm install
    - echo "Запускаем lint тест..."
    - pnpm run lint
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store

#test_backend:
#  stage: test
#  image: python:3.9-slim
#  cache:
#    key: backend-deps
#    paths:
#      - backend/.venv/
#  before_script:
#    - apt-get update && apt-get upgrade -y
#  script:
#    - echo "Устанавливаем зависимости и запускаем тесты..."
#    - cd backend
#    - python -m venv .venv
#    - source .venv/bin/activate
#    - pip install --upgrade pip
#    - pip install -r requirements.txt
#    - python -m pytest

deploy:
  stage: deploy
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 400 ~/.ssh/id_rsa
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
    - echo "StrictHostKeyChecking no" >> ~/.ssh/config
  script:
    - echo "Деплоим на сервер..."
    - ssh $SERVER_USER@$SERVER_IP -p 2222 "
      echo $HARBOR_PASSWORD | docker login $HARBOR_URL -u $HARBOR_USER --password-stdin &&
      cd /home/ais-project/fuel_forecast_app/ &&
      docker compose down &&
      docker compose pull &&
      docker compose up -d
      "
