stages:
  - build
  - test
  - deploy

variables:
  FRONTEND_IMAGE: frontend
  BACKEND_IMAGE: backend
  NGINX_IMAGE: nginx
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA

build_frontend:
  stage: build
  script:
    - echo "Сборка frontend контейнера..."
    - docker build -t $FRONTEND_IMAGE:$IMAGE_TAG ./frontend
    - docker tag $FRONTEND_IMAGE:$IMAGE_TAG $HARBOR_URL/$HARBOR_PROJECT/$FRONTEND_IMAGE:$IMAGE_TAG
    - docker login $HARBOR_URL -u $HARBOR_USER -p $HARBOR_PASSWORD
    - docker push $HARBOR_URL/$HARBOR_PROJECT/$FRONTEND_IMAGE:$IMAGE_TAG

build_backend:
  stage: build
  script:
    - echo "Сборка backend контейнера..."
    - docker build -t $BACKEND_IMAGE:$IMAGE_TAG ./backend
    - docker tag $BACKEND_IMAGE:$IMAGE_TAG $HARBOR_URL/$HARBOR_PROJECT/$BACKEND_IMAGE:$IMAGE_TAG
    - docker login $HARBOR_URL -u $HARBOR_USER -p $HARBOR_PASSWORD
    - docker push $HARBOR_URL/$HARBOR_PROJECT/$BACKEND_IMAGE:$IMAGE_TAG

build_nginx:
  stage: build
  script:
    - echo "Сборка nginx контейнера..."
    - docker build -t $NGINX_IMAGE:$IMAGE_TAG ./nginx
    - docker tag $NGINX_IMAGE:$IMAGE_TAG $HARBOR_URL/$HARBOR_PROJECT/$NGINX_IMAGE:$IMAGE_TAG
    - docker login $HARBOR_URL -u $HARBOR_USER -p $HARBOR_PASSWORD
    - docker push $HARBOR_URL/$HARBOR_PROJECT/$NGINX_IMAGE:$IMAGE_TAG

test_frontend:
  stage: test
  script:
    - echo "Запускаем lint тест..."
    - cd frontend && npm install && npm run lint

test_backend:
  stage: test
  script:
    - echo "Запускаем backend pytest..."
    - cd backend && pip install -r requirements.txt && python -m pytest

deploy:
  stage: deploy
  before_script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo "StrictHostKeyChecking no" >> ~/.ssh/config
  script:
    - echo "Деплоим на сервер..."
    - ssh $SERVER_USER@$SERVER_IP "      
        docker login $HARBOR_URL -u $HARBOR_USER -p $HARBOR_PASSWORD &&
        docker-compose down &&
        docker-compose pull &&
        docker-compose up -d
      "
  only:
    - main  # Запускать только для ветки main