stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2

build:
  stage: build
  script:
    - echo "Building Docker images..."
    - docker-compose build

test:
  stage: test
  script:
    - echo "Running tests..."
    - docker-compose up -d
    - docker-compose exec backend python -m pytest

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    - docker-compose up -d
  only:
    - main