version: '3.8'

services:
  frontend:
    build: harbor.ogsneaky.ru:8443/fuel_app/frontend:latest
    ports:
      - '3001:80'
    depends_on:
      - backend

  backend:
    build: harbor.ogsneaky.ru:8443/fuel_app/backend:latest
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app

  nginx:
    build: harbor.ogsneaky.ru:8443/fuel_app/nginx:latest
    ports:
      - '8080:80'
    depends_on:
      - frontend
      - backend
