version: '3.8'

services:
  frontend:
    build: fuel_app_frontend
    ports:
      - '3001:3001'
    environment:
      - VITE_PORT=3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["pnpm", "run", "dev"]
    depends_on:
      - backend

  backend:
    image: fuel_app_backend
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://admin:MOuust2025@db:5432/fuel_db
  db:
    image: harbor.ogsneaky.ru:8443/fuel_app/postgresql:13.18-19
    container_name: fuel_db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: fuel_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: MOuust2025
    volumes:
      - pgdata:/var/lib/postgresql/data
  nginx:
    build: harbor.ogsneaky.ru:8443/fuel_app/nginx:latest
    ports:
      - '8080:80'
    depends_on:
      - frontend
      - backend
volumes:
  pgdata: