# Generated by Django 4.2 on 2025-02-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_calc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
