# Generated by Django 4.2 on 2025-02-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_calc', '0003_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_images/'),
        ),
    ]
